language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - 'node_modules'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install codecov.io coveralls request lerna@^3.18.3
script:
  - yarn test

after_success:
  - yarn run coverage:combine
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
