language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - 'node_modules'
script:
  - yarn test

after_success:
  - yarn run coverage:combine
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
