language: node_js
node_js:
  - '12'
before_install:
  - npm install codecov.io coveralls request lerna
cache:
  directories:
    - 'node_modules'
script:
  - npm test
after_success:
  - npm run coverage:combine
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
