import { relayStylePagination } from "@apollo/client/utilities";

// This example shows how you can configure Apollo Client to understand
// how pagination works in the GraphQL API service. Apollo suggests to use
// the "relayStylePagination" client, passing in key args that differentiate
// queries so that they can be merged together. We add the @connection directive
// also so we can differentiate our our queries that should be merged seperately

export const typePolicies = {
  Collection: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      items: relayStylePagination([
        "bounds",
        "boundsCircle",
        "externalIds",
        "externalSources",
        "keyword",
        "resourceIds",
        "sectionIds",
        "sort",
        "tags",
        "@connection",
        ["key"],
      ]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  CollectionLocation: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  IconSilhouette: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
    },
  },
  Itinerary: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      children: relayStylePagination([
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      descendants: relayStylePagination([
        "depthMax",
        "depthMin",
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      icons: relayStylePagination(["@connection", ["key"]]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  ItineraryCollection: {
    fields: {
      ancestors: relayStylePagination([
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      children: relayStylePagination([
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      descendants: relayStylePagination([
        "depthMax",
        "depthMin",
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  ItineraryDirections: {
    fields: {
      ancestors: relayStylePagination([
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      children: relayStylePagination([
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      descendants: relayStylePagination([
        "depthMax",
        "depthMin",
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  ItineraryItemEdge: {
    fields: {
      directions: relayStylePagination([
        "direction",
        "limitImmediate",
        "skipOptional",
        "@connection",
        ["key"],
      ]),
    },
  },
  ItineraryLocation: {
    fields: {
      ancestors: relayStylePagination([
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      children: relayStylePagination([
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      descendants: relayStylePagination([
        "depthMax",
        "depthMin",
        "parentType",
        "placeIds",
        "segmentIds",
        "type",
        "@connection",
        ["key"],
      ]),
      directions: relayStylePagination([
        "accuracy",
        "direction",
        "restrict",
        "segmentIds",
        "@connection",
        ["key"],
      ]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  MediaImage: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
    },
  },
  Place: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      mediaContainers: relayStylePagination(["@connection", ["key"]]),
    },
  },
  PlaceHours: {
    fields: {
      intervals: relayStylePagination([
        "from",
        "offset",
        "status",
        "to",
        "@connection",
        ["key"],
      ]),
    },
  },
  Position: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
    },
  },
  Profile: {
    fields: {
      attrs: relayStylePagination([
        "id",
        "includeNoLocale",
        "locale",
        "@connection",
        ["key"],
      ]),
      billingSubscriptions: relayStylePagination(["@connection", ["key"]]),
      connectedApps: relayStylePagination([
        "authType",
        "deleted",
        "expired",
        "serviceKey",
        "type",
        "@connection",
        ["key"],
      ]),
      followers: relayStylePagination([
        "handle",
        "status",
        "@connection",
        ["key"],
      ]),
      following: relayStylePagination([
        "handle",
        "status",
        "@connection",
        ["key"],
      ]),
    },
  },
  Query: {
    fields: {
      authorizedProfiles: relayStylePagination(["@connection", ["key"]]),
      billingPrices: relayStylePagination(["@connection", ["key"]]),
      billingSubscriptions: relayStylePagination([
        "profileId",
        "@connection",
        ["key"],
      ]),
      collectionItems: relayStylePagination([
        "bounds",
        "boundsCircle",
        "collectionIds",
        "externalIds",
        "externalSources",
        "keyword",
        "placeIds",
        "profileId",
        "resourceIds",
        "sectionIds",
        "sort",
        "tags",
        "@connection",
        ["key"],
      ]),
      collections: relayStylePagination([
        "discriminator",
        "profileId",
        "sort",
        "@connection",
        ["key"],
      ]),
      connectedApps: relayStylePagination([
        "authType",
        "deleted",
        "expired",
        "profileId",
        "serviceKey",
        "type",
        "@connection",
        ["key"],
      ]),
      iconResources: relayStylePagination([
        "profileId",
        "@connection",
        ["key"],
      ]),
      itineraries: relayStylePagination([
        "keyword",
        "profileId",
        "sort",
        "@connection",
        ["key"],
      ]),
      placeAddressSearch: relayStylePagination([
        "borough",
        "country",
        "county",
        "layers",
        "locality",
        "maxLabelLength",
        "neighbourhood",
        "postalCode",
        "region",
        "sources",
        "streetAddress",
        "thirdPartyQuery",
        "@connection",
        ["key"],
      ]),
      placeAutocompleteSearch: relayStylePagination([
        "bounds",
        "focus",
        "layers",
        "maxLabelLength",
        "sources",
        "text",
        "thirdPartyQuery",
        "@connection",
        ["key"],
      ]),
      placeReverseSearch: relayStylePagination([
        "focus",
        "layers",
        "maxLabelLength",
        "sources",
        "thirdPartyQuery",
        "@connection",
        ["key"],
      ]),
      placeSearch: relayStylePagination([
        "bounds",
        "focus",
        "layers",
        "maxLabelLength",
        "sources",
        "text",
        "thirdPartyQuery",
        "@connection",
        ["key"],
      ]),
      profiles: relayStylePagination(["handle", "@connection", ["key"]]),
      routes: relayStylePagination([
        "mode",
        "positions",
        "@connection",
        ["key"],
      ]),
      userAgreements: relayStylePagination([
        "profileId",
        "@connection",
        ["key"],
      ]),
    },
  },
};
